---
- name: Ensure the Onyx path exists
  file:
    path: "{{ onyx_path }}"
    state: directory
    mode: 0755
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    recurse: yes

- name: Transfer the Docker image to the cluster machine
  synchronize:
    src: "{{ docker_image }}"
    dest: "{{ onyx_path }}/{{ onyx_image_file }}"

- name: Install the Docker image
  shell: "docker load -i {{ onyx_path }}/{{ onyx_image_file }}"

- include: start.yml